### ISSUE TITLE
Is it possible to reboot after hibernating?

### ISSUE THREAD

**Issue by hradec** [bfleischer/hibernate#1]
I'm wonderig if its possible to reboot the machine after hibernating, so it can netboot to a different OS.

I already use bless to netboot a Mac to Linux, but currently the script  just reboots after the bless.

i 'm looking for a way to hibernate and reboot after bless, so when we reboot back from Linux, OSX would resume! 

do you think adding a reboot call at the end of your main() would do the trick?

**Comment by bfleischer** [comment]
I don't think this would work. The tool alters the power preferences to enable hibernation, tells macOS to go to sleep and then waits until macOS has been resumed to restore the previous power preferences. At the end of the main() function macOS has already been resumed.
